clc
clear
close all
%% Canteliver example
%**************************************************************************
% Material properties
% Emax = Modulus of elasticity for solid state
% Emin = Modulus of elasticity for void state
% v = Possion ratio
% P is power of volume fraction in ersatz material model
% Colors specifies material color
MP = struct("Emax",[3,5],...
            "Emin",1e-3,...
            "v",0.3, ...
            "P",1.5,...
            "Colors",[1,0,0;0,1,0;0,0,1]);
%**************************************************************************
% Geometry properties
% ngp = number of gaussian points at each direction
% nor = Number of rectangle
% noph = Number of phases
% els = Element size for each direction
% X0 and Y0  are coordiate of left-bottom-back points for each rectangle
% lx and ly are lengths of each rectangle
% EBC is essential boundary conditions [x0,x1,y0,y1,Disx,Disy]
% NBC is necessary boundary conditions [x0,x1,y0,y1,fx,fy]
GP = struct("ngp",4,...
            "nor",1,...
            "noph",2,...
            "els",1,...
            "X0",0,"Y0",0,...
            "lx",60,"ly",30,...
            "EBC",[0,0,0,30,0,0],...
            "NBC",[60,60,15,15,0,-1]);
%**************************************************************************
% Optimization parameters
% NOI = Number or iterations
% Tho and delta_T are LSM parameters


% VC0 = Volume constraint value
% Mu, nRelax, Gamma, dGamma are Augmented Lagrangian parameters
% PlotResults is used for showing results in optimization iterations
OP = struct("NOI",350,...
            "Tho",0.4,...
            "delta_T",0.05,...
            "VC0",[0.25,0.25],...
            "Mu",[4,4], ...
            "nRelax",25*[1,1], ...
            "Gamma",[0.5,0.5],...
            "dGamma",[0.05,0.05], ...
            "maxGamma",[5,5], ...
            "Lambda",[0,0], ...
            "PlotResult",1);
%% Optimization
%Topology optimization of multi material model with 
% reaction diffusion level set method
TO_MMRDLSM
%***********************************************************************END